-- H2 2.3.232; 
;              
CREATE USER IF NOT EXISTS "ADMIN" SALT 'c241ee334b04a1f7' HASH '65dd813cb1d21da8045617f3701c8a55c61a0d7dd8e5d0bfe2ee93573caad24d' ADMIN;       
CREATE MEMORY TABLE "PUBLIC"."DAILY_CHALLENGES"(
    "CHALLENGE_DATE" DATE NOT NULL,
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "EXERCISE_ID" UUID NOT NULL
);               
ALTER TABLE "PUBLIC"."DAILY_CHALLENGES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1CD" PRIMARY KEY("ID");            
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.DAILY_CHALLENGES;         
CREATE MEMORY TABLE "PUBLIC"."EXERCISES"(
    "VERIFIED" BOOLEAN NOT NULL,
    "CREATED_AT" TIMESTAMP(6) NOT NULL,
    "PROGRAMMING_LANG_ID" BIGINT NOT NULL,
    "ID" UUID NOT NULL,
    "TITLE" CHARACTER VARYING(100) NOT NULL,
    "CREATOR_ID" CHARACTER VARYING(255) NOT NULL,
    "DESCRIPTION" CHARACTER VARYING,
    "DIFFICULTY" ENUM('EASY', 'HARD', 'MEDIUM') NOT NULL,
    "MAIN_CODE" CHARACTER LARGE OBJECT
);  
ALTER TABLE "PUBLIC"."EXERCISES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" PRIMARY KEY("ID");     
-- 5 +/- SELECT COUNT(*) FROM PUBLIC.EXERCISES;
INSERT INTO "PUBLIC"."EXERCISES" VALUES
(FALSE, TIMESTAMP '2025-07-23 12:39:57.908792', 2, UUID '00693516-56ae-4e19-8cf7-d56c77f72755', U&'Soma de Dois N\00fameros', 'admin', U&'Crie uma fun\00e7\00e3o que receba dois n\00fameros inteiros como par\00e2metro e retorne a soma deles.', 'EASY', U&'import sys\000aa = int(sys.argv[1])\000ab = int(sys.argv[2])\000adef sum(a,b):\000a\0009{user_code}\000aprint(sum(a,b))'),
(FALSE, TIMESTAMP '2025-07-23 12:43:24.018139', 2, UUID '8e86ede0-2b8b-4ae9-b573-d8bccc03ccc0', U&'Verificar Pal\00edndromo', 'admin', U&'Crie uma fun\00e7\00e3o que receba uma string como par\00e2metro e retorne True se ela for um pal\00edndromo, e False caso contr\00e1rio. Um pal\00edndromo \00e9 uma palavra ou frase que \00e9 a mesma quando lida de tr\00e1s para frente, desconsiderando espa\00e7os e mai\00fasculas/min\00fasculas.', 'MEDIUM', U&'import sys\000as = sys.argv[1]\000adef is_palindrome(s):\000a\0009{user_code}\000aprint(is_palindrome(s))'),
(FALSE, TIMESTAMP '2025-07-23 12:43:41.914615', 1, UUID '1d74600e-dd5d-4d3b-8224-1d2632644571', 'Calcular Fatorial', 'admin', U&'Crie um m\00e9todo que receba um n\00famero inteiro n\00e3o-negativo ''n'' como par\00e2metro e retorne o seu fatorial. O fatorial de um n\00famero \00e9 o produto de todos os inteiros de 1 at\00e9 o pr\00f3prio n\00famero. O fatorial de 0 \00e9 1.', 'HARD', U&'public class Solution {\000a    public static long factorial(int n) {\000a        // Seu c\00f3digo aqui\000a        {user_code}\000a    }\000a\000a    public static void main(String[] args) {\000a        if (args.length > 0) {\000a            int num = Integer.parseInt(args[0]);\000a            System.out.println(factorial(num));\000a        }\000a    }\000a}'),
(FALSE, TIMESTAMP '2025-07-23 12:44:10.232262', 2, UUID 'ea465035-1917-4824-8ba9-d69673040798', 'Inverter uma String', 'admin', U&'Crie uma fun\00e7\00e3o que receba uma string como par\00e2metro e a retorne invertida. Por exemplo, se a entrada for ''hello'', a sa\00edda deve ser ''olleh''.', 'EASY', U&'import sys\000as = sys.argv[1]\000adef reverse_string(s):\000a\0009{user_code}\000aprint(reverse_string(s))'),
(FALSE, TIMESTAMP '2025-07-23 12:44:21.259868', 2, UUID 'b48e5da6-4cd1-49a9-a390-e6b6358d3c2e', U&'Encontrar o N\00famero Faltante', 'admin', U&'Voc\00ea recebe uma lista de ''n-1'' inteiros, e esses inteiros est\00e3o no intervalo de 1 a ''n''. N\00e3o h\00e1 duplicatas na lista. Um dos inteiros est\00e1 faltando. Crie uma fun\00e7\00e3o que encontre o inteiro que falta. Os n\00fameros ser\00e3o passados como argumentos de linha de comando.', 'MEDIUM', U&'import sys\000anums_str = sys.argv[1:]\000anums = [int(n) for n in nums_str]\000adef find_missing_number(nums):\000a\0009{user_code}\000aprint(find_missing_number(nums))');              
CREATE MEMORY TABLE "PUBLIC"."PROGRAMMING_LANGUAGES"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 5) NOT NULL,
    "API_IDENTIFIER" CHARACTER VARYING(50) NOT NULL,
    "NAME" CHARACTER VARYING(50) NOT NULL
);
ALTER TABLE "PUBLIC"."PROGRAMMING_LANGUAGES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7F98" PRIMARY KEY("ID");      
-- 4 +/- SELECT COUNT(*) FROM PUBLIC.PROGRAMMING_LANGUAGES;    
INSERT INTO "PUBLIC"."PROGRAMMING_LANGUAGES" VALUES
(1, 'java', 'Java'),
(2, 'python', 'Python'),
(3, 'c', 'C'),
(4, 'cpp', 'C++');            
CREATE MEMORY TABLE "PUBLIC"."TEST_CASES"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 19) NOT NULL,
    "EXERCISE_ID" UUID NOT NULL,
    "EXPECTED_OUTPUT" CHARACTER VARYING NOT NULL,
    "INPUT_DATA" CHARACTER VARYING
);   
ALTER TABLE "PUBLIC"."TEST_CASES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_C" PRIMARY KEY("ID");    
-- 18 +/- SELECT COUNT(*) FROM PUBLIC.TEST_CASES;              
INSERT INTO "PUBLIC"."TEST_CASES" VALUES
(1, UUID '00693516-56ae-4e19-8cf7-d56c77f72755', '15', '5, 10'),
(2, UUID '00693516-56ae-4e19-8cf7-d56c77f72755', '0', '-1, 1'),
(3, UUID '00693516-56ae-4e19-8cf7-d56c77f72755', '0', '0, 0'),
(4, UUID '8e86ede0-2b8b-4ae9-b573-d8bccc03ccc0', 'True', 'arara'),
(5, UUID '8e86ede0-2b8b-4ae9-b573-d8bccc03ccc0', 'True', 'Anotaram a data da maratona'),
(6, UUID '8e86ede0-2b8b-4ae9-b573-d8bccc03ccc0', 'False', 'python'),
(7, UUID '1d74600e-dd5d-4d3b-8224-1d2632644571', '120', '5'),
(8, UUID '1d74600e-dd5d-4d3b-8224-1d2632644571', '1', '0'),
(9, UUID '1d74600e-dd5d-4d3b-8224-1d2632644571', '3628800', '10'),
(10, UUID '1d74600e-dd5d-4d3b-8224-1d2632644571', '1', '1'),
(11, UUID 'ea465035-1917-4824-8ba9-d69673040798', 'olleh', 'hello'),
(12, UUID 'ea465035-1917-4824-8ba9-d69673040798', 'nohtyP', 'Python'),
(13, UUID 'ea465035-1917-4824-8ba9-d69673040798', 'a', 'a'),
(14, UUID 'ea465035-1917-4824-8ba9-d69673040798', '54321', '12345'),
(15, UUID 'b48e5da6-4cd1-49a9-a390-e6b6358d3c2e', '3', '1 2 4 5'),
(16, UUID 'b48e5da6-4cd1-49a9-a390-e6b6358d3c2e', '4', '2 3 1 5'),
(17, UUID 'b48e5da6-4cd1-49a9-a390-e6b6358d3c2e', '8', '9 6 4 2 3 5 7 1'),
(18, UUID 'b48e5da6-4cd1-49a9-a390-e6b6358d3c2e', '2', '1');
CREATE MEMORY TABLE "PUBLIC"."USERS"(
    "DAILY_STREAK" INTEGER,
    "EMAIL" CHARACTER VARYING(255) NOT NULL,
    "PASSWORD" CHARACTER VARYING(255) NOT NULL,
    "USERNAME" CHARACTER VARYING(255) NOT NULL,
    "ROLE" CHARACTER VARYING(255) DEFAULT 'USER' NOT NULL
);    
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4D" PRIMARY KEY("USERNAME");  
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.USERS;    
INSERT INTO "PUBLIC"."USERS" VALUES
(0, 'admin@example.com', '$2a$10$U44F83hmdVv1mSdljHJfMuCn3FtQUCHNpRWTAUGlFgGlrB.HGK3z2', 'admin', 'ADMIN'),
(0, 'user@example.com', '$2a$10$SeJw56gygIXMiLHNlk8Gqu/lJU3TFXJg2g8WLHEi7hf7R78oOKnO.', 'user', 'USER');       
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" UNIQUE NULLS DISTINCT ("EMAIL");           
ALTER TABLE "PUBLIC"."PROGRAMMING_LANGUAGES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7F9" UNIQUE NULLS DISTINCT ("NAME");          
ALTER TABLE "PUBLIC"."DAILY_CHALLENGES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" UNIQUE NULLS DISTINCT ("CHALLENGE_DATE");       
ALTER TABLE "PUBLIC"."PROGRAMMING_LANGUAGES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7F" UNIQUE NULLS DISTINCT ("API_IDENTIFIER"); 
ALTER TABLE "PUBLIC"."DAILY_CHALLENGES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1C" UNIQUE NULLS DISTINCT ("EXERCISE_ID");         
ALTER TABLE "PUBLIC"."TEST_CASES" ADD CONSTRAINT "PUBLIC"."FKGQTQQ49JN0RFQTW5V40GCMLU6" FOREIGN KEY("EXERCISE_ID") REFERENCES "PUBLIC"."EXERCISES"("ID") NOCHECK;              
ALTER TABLE "PUBLIC"."DAILY_CHALLENGES" ADD CONSTRAINT "PUBLIC"."FKO2I0420UYK0HYLP7UVGGLR5OV" FOREIGN KEY("EXERCISE_ID") REFERENCES "PUBLIC"."EXERCISES"("ID") NOCHECK;        
ALTER TABLE "PUBLIC"."EXERCISES" ADD CONSTRAINT "PUBLIC"."FKS6XREE4VWJ2YTCDSXY5V3XWK2" FOREIGN KEY("CREATOR_ID") REFERENCES "PUBLIC"."USERS"("USERNAME") NOCHECK;              
ALTER TABLE "PUBLIC"."EXERCISES" ADD CONSTRAINT "PUBLIC"."FK83MSU0JXBKWTGT0N6CQ6XAP9J" FOREIGN KEY("PROGRAMMING_LANG_ID") REFERENCES "PUBLIC"."PROGRAMMING_LANGUAGES"("ID") NOCHECK;           
