POST http://localhost:8084/auth/register
Content-Type: application/json

{
  "username": "adesto",
  "email": "adesto@example.com",
  "password": "12346678",
  "role": "ADMIN"
}

###

POST http://localhost:8084/auth/login
Content-Type: application/json

{
  "email": "adesto@example.com",
  "password": "12346678"
}

###

POST http://localhost:8084/auth/register
Content-Type: application/json

{
  "username": "banTest",
  "email": "banTest@example.com",
  "password": "12346678",
  "role": "USER"
}

###

POST http://localhost:8084/auth/login
Content-Type: application/json

{
  "email": "banTest@example.com",
  "password": "12346678"
}

### BANIMENTO

PATCH http://localhost:8084/users/banTest/ban
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZGVzdG8iLCJpYXQiOjE3NTM3MTEzNjAsImV4cCI6MTc1Mzc5Nzc2MH0.AkIBAbKb8V_JBZU7mFcCn47pvAH25f9-WX1n-V6ExMk

{
  "banReason": "TESTE TESTE TESTE"
}

### UNBAN

PATCH http://localhost:8084/users/banTest/unban
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZGVzdG8iLCJpYXQiOjE3NTM3MTEzNjAsImV4cCI6MTc1Mzc5Nzc2MH0.AkIBAbKb8V_JBZU7mFcCn47pvAH25f9-WX1n-V6ExMk

### TIMEOUT

PATCH http://localhost:8084/users/banTest/timeout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZGVzdG8iLCJpYXQiOjE3NTM3MTEzNjAsImV4cCI6MTc1Mzc5Nzc2MH0.AkIBAbKb8V_JBZU7mFcCn47pvAH25f9-WX1n-V6ExMk

{
  "reason": "TESTE TIMEOUT",
  "durationMinutes": 5
}

### CLEAR TIMEOUT

PATCH http://localhost:8084/users/banTest/untimeout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZGVzdG8iLCJpYXQiOjE3NTM3MTEzNjAsImV4cCI6MTc1Mzc5Nzc2MH0.AkIBAbKb8V_JBZU7mFcCn47pvAH25f9-WX1n-V6ExMk

###

POST http://localhost:8084/exercises
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiYW5UZXN0IiwiaWF0IjoxNzUzNzExNjE1LCJleHAiOjE3NTM3OTgwMTV9.WtRHbN26N7NKG1Upnu6IVMEWyEjcPVQbr-pCvVD2mSg

{
    "title": "Soma de Dois Números",
    "description": "Crie uma função que receba dois números inteiros como parâmetro e retorne a soma deles.",
    "mainCode": "public class Solution {\n    public int somar(int a, int b) {\n        // Seu código aqui\n        return 0;\n    }\n}",
    "difficulty": "EASY",
    "languageId": 3,
    "testCases": [
        {
            "input": "5, 10",
            "expectedOutput": "15"
        },
        {
            "input": "-1, 1",
            "expectedOutput": "0"
        },
        {
            "input": "0, 0",
            "expectedOutput": "0"
        }
    ]
}

###

POST http://localhost:8084/exercises/84b0e24d-cf92-42c4-b813-ba3450199234/solve
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZGVzdG8xMiIsImlhdCI6MTc1Mjg4NDg4MCwiZXhwIjoxNzUyOTcxMjgwfQ.MAFtpT75jBZdPtdHY05Xw3UN8sP9Ueq3hIHBbNzGOeM

{
  "userCode": "public int solve(int a, int b) { return a + b; }",
  "inputs": ["2", "3"],
  "language": "java"
}

###

GET http://localhost:8084/exercises/{id}
Content-Type: application/json
Authorization: Bearer {token} 