###
POST http://localhost:8084/auth/register
Content-Type: application/json

{
  "username": "adesto",
  "email": "adesto@example.com",
  "password": "12346678",
  "role": "ADMIN"
}

###
POST http://localhost:8084/auth/login
Content-Type: application/json

{
  "email": "adesto@example.com",
  "password": "12346678"
}

###
POST http://localhost:8084/auth/register
Content-Type: application/json

{
  "username": "banTest",
  "email": "banTest@example.com",
  "password": "12346678",
  "role": "USER"
}

###
POST http://localhost:8084/auth/login
Content-Type: application/json

{
  "email": "banTest@example.com",
  "password": "12346678"
}

###
PATCH http://localhost:8084/users/banTest/ban
Content-Type: application/json
Authorization: Bearer {{admin_token}}

{
  "banReason": "TESTE TESTE TESTE"
}

###
PATCH http://localhost:8084/users/banTest/unban
Content-Type: application/json
Authorization: Bearer {{admin_token}}

###
PATCH http://localhost:8084/users/banTest/timeout
Content-Type: application/json
Authorization: Bearer {{admin_token}}

{
  "reason": "TESTE TIMEOUT",
  "durationMinutes": 5
}

###
PATCH http://localhost:8084/users/banTest/untimeout
Content-Type: application/json
Authorization: Bearer {{admin_token}}

###
POST http://localhost:8084/exercises
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiYW5UZXN0IiwiaWF0IjoxNzUzOTEwNDM4LCJleHAiOjE3NTM5OTY4Mzh9.mc5mVQrW_9iQPWwmzIbL5s4RyY0aY4tisuh6sOPVeXg

{
  "title": "Soma de Dois Números",
  "description": "Crie uma função que receba dois números e retorne a soma.",
  "mainCode": "public class Solution {\n    public int somar(int a, int b) {\n        // Seu código\n        return {user_code};\n    }\n}",
  "difficulty": "EASY",
  "languageId": 1,
  "testCases": [
    { "input": "5 10", "expectedOutput": "15" },
    { "input": "-1 1", "expectedOutput": "0" }
  ]
}

###
# 10. Listar exercícios filtrando por linguagem “Java”
GET http://localhost:8084/exercises?language=Java&page=0&size=1
Content-Type: application/json

###
# 11. Buscar exercício por ID
GET http://localhost:8084/exercises/0a2c5fa9-0a66-42ac-9cec-a4458e43f911
Content-Type: application/json

###
# 12. Submeter solução para exercício (solve)
POST http://localhost:8084/exercises/16e51e3c-84fc-492b-8780-074c354fb630/solve
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiYW5UZXN0IiwiaWF0IjoxNzUzOTEwNDM4LCJleHAiOjE3NTM5OTY4Mzh9.mc5mVQrW_9iQPWwmzIbL5s4RyY0aY4tisuh6sOPVeXg

{
  "code": "public int somar(int a, int b) { return a + b; }"
}

###
# 13. Upvote no exercício
POST http://localhost:8084/exercises/0a2c5fa9-0a66-42ac-9cec-a4458e43f911/upvote
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiYW5UZXN0IiwiaWF0IjoxNzUzOTEwNDM4LCJleHAiOjE3NTM5OTY4Mzh9.mc5mVQrW_9iQPWwmzIbL5s4RyY0aY4tisuh6sOPVeXg

###
# 14. Downvote no exercício
POST http://localhost:8084/exercises/0a2c5fa9-0a66-42ac-9cec-a4458e43f911/downvote
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiYW5UZXN0IiwiaWF0IjoxNzUzOTEwNDM4LCJleHAiOjE3NTM5OTY4Mzh9.mc5mVQrW_9iQPWwmzIbL5s4RyY0aY4tisuh6sOPVeXg

###
# 15. Criar lista de exercícios para o usuário banTest
POST http://localhost:8084/users/banTest/lists
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiYW5UZXN0IiwiaWF0IjoxNzUzOTEwNDM4LCJleHAiOjE3NTM5OTY4Mzh9.mc5mVQrW_9iQPWwmzIbL5s4RyY0aY4tisuh6sOPVeXg

{
  "name": "Minhas Listas Legais",
  "exerciseIds": ["0a2c5fa9-0a66-42ac-9cec-a4458e43f911"]
}

###
# 16. Listar todas as listas de banTest
GET http://localhost:8084/users/banTest/lists
Content-Type: application/json
Authorization: Bearer {{user_token}}

###
# 17. Buscar lista específica por ID
GET http://localhost:8084/users/banTest/lists/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiYW5UZXN0IiwiaWF0IjoxNzUzOTEwNDM4LCJleHAiOjE3NTM5OTY4Mzh9.mc5mVQrW_9iQPWwmzIbL5s4RyY0aY4tisuh6sOPVeXg
