POST http://localhost:8084/auth/register
Content-Type: application/json

{
  "username": "adesto",
  "email": "adesto@example.com",
  "password": "12346678",
  "role": "ADMIN"
}

###

POST http://localhost:8084/auth/login
Content-Type: application/json

{
  "email": "adesto@example.com",
  "password": "12346678"
}

###

GET

###

POST http://localhost:8084/exercises
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZGVzdG8iLCJpYXQiOjE3NTI3OTcyOTUsImV4cCI6MTc1Mjg4MzY5NX0.7zOjlq7MKfJgUWVBRuq55_LOhtDHXw-bt9u4FDXr7VM

{
  "title": "Soma de Dois Números",
  "language": "java",
  "difficulty": "EASY",
  "description": "Dado dois inteiros, retorne a soma.",
  "mainCode": "public int solve(int a, int b) { /* seu código aqui */ }",
  "testCode": "assert solve(2,3) == 5; assert solve(-1,1) == 0;"
}

###

POST http://localhost:8084/exercises/00a9f823-3a79-4b4f-a242-56d2bb5b6699/solve
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZGVzdG8iLCJpYXQiOjE3NTI3OTcyOTUsImV4cCI6MTc1Mjg4MzY5NX0.7zOjlq7MKfJgUWVBRuq55_LOhtDHXw-bt9u4FDXr7VM

{
  "userCode": "public int solve(int a, int b) { return a + b; }",
  "inputs": ["2", "3"],
  "language": "java"
}
